# HarperDB configuration file. Refer to https://harperdb.io/docs/reference/configuration-file/
---
http:
  compressionThreshold: 0
  cors: true
  corsAccessList:
    - "*"
  keepAliveTimeout: 30000
  port: 9926
  securePort: null
  mtls: false
  http2: false
  timeout: 120000
threads:
  count: 1
  debug: true
authentication:
  authorizeLocal: true
  cacheTTL: 30000
  enableSessions: true
  operationTokenTimeout: 1d
  refreshTokenTimeout: 30d
analytics:
  aggregatePeriod: 60
  replicate: false
replication:
  securePort: 9933
  enableRootCAs: true
  hostname: localhost
  databases: '*' # Database name or list of database names to replicate, * defaults to all databases
  routes: null
componentsRoot: /Users/ivan/hdb/components
localStudio:
  enabled: true
logging:
  auditAuthEvents:
    logFailed: false
    logSuccessful: false
  auditLog: true
  auditRetention: 3d
  file: true
  level: info
  root: /Users/ivan/hdb/log
  rotation:
    enabled: true
    compress: false
    interval: null
    maxSize: 64M
    path: /Users/ivan/hdb/log
  stdStreams: true
mqtt:
  network:
    port: 1883
    securePort: 8883
    mtls: false
  webSocket: true
  requireAuthentication: true
operationsApi:
  network:
    cors: true
    corsAccessList:
      - '*'
    domainSocket: /Users/ivan/hdb/operations-server
    port: 9925
    securePort: null
rootPath: /Users/ivan/Projects/harper-edge-ai-personalization-example/harper-components
storage:
  writeAsync: false
  caching: true
  compression: true
  noReadAhead: false
  path: /Users/ivan/hdb/database
  prefetchWrites: true
tls:
  privateKey: /Users/ivan/hdb/keys/privateKey.pem
